export const RESOURCE = {
  AUTH: "Auth",
  PRODUCTION: "production",
  DEVELOPMENT: "development",
  INTERNAL_SERVER_ERROR: "Internal server error",
  API: "api",
  V1: "/v1",
  IMAGES: "projectImages",
  ID: "_id",
  ROLES: "roles",
  TESTS: "tests",
  TEST: "test",
  TEST_CHILD: "testChild",
  USERS: "users",
};
